services:
  - type: web
    name: 4t1-services
    runtime: python
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "python -m gunicorn fortione_services.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
